# This file is a template, and might need editing before it works on your project.
# Select image from https://hub.docker.com/_/php/
image: registry.gitlab.com/fpilee/ci-test:v0.1

# Select what we should cache between builds
cache:
  paths:
  - vendor/

stages:
  - build
  - test

# Run our tests
# If Xdebug was installed you can generate a coverage report and see code coverage metrics.
build:
  stage: build
  script:
  - docker build -t my-image .
  - docker tag my-image registry.gitlab.com/fpilee/ci-test:v0.2
  - docker push registry.gitlab.com/fpilee/ci-test:v0.2

test:
  stage: test
  script:
  - composer install
  - vendor/bin/phpunit --configuration phpunit.xml --coverage-text --colors=never